language: python

sudo: required

services:
  - docker

python:
  - "2.7"

before_install:
  # run reszelaz/sardana-test docker container (Debian8 with sardana-deps)
  - docker pull reszelaz/sardana-test
  - docker run -d --name=sardana-test -h sardana-test --volume=`pwd`:/sardana reszelaz/sardana-test
  # wait approx. 10 s (supervisor starts mysql and Tango DB)
  - sleep 10
  # install sardana in order to create the launcher scripts for servers
  - docker exec sardana-test bash -c "cd /sardana && python setup.py install"
  # start Pool and MacroServer necessary for macro tests
  - docker exec sardana-test which Pool
  - docker exec sardana-test supervisorctl start Pool
  - docker exec sardana-test supervisorctl start MacroServer
  #- docker exec -d sardana-test Pool demo1
  #- sleep 3
  #- docker exec -d sardana-test MacroServer demo1
  #- sleep 3
  - docker exec sardana-test ps -ef
  - docker exec sardana-test ls /tmp
  - docker exec sardana-test ls /tmp/tango-root
  - docker exec sardana-test ls /tmp/tango-root/Pool/
  - docker exec sardana-test ls /tmp/tango-root/MacroServer/
  - docker exec sardana-test ls /tmp/tango-root/Pool/demo1
  - docker exec sardana-test ls /tmp/tango-root/MacroServer/demo1
  
script:
  # run the full testsuite
  - docker exec sardana-test sardanatestsuite
